fix: prevent overwriting i18n.json for unsupported locales
replexica/replexica pull request #245
Opened 2024-10-16 18:03 UTC by Nithishvb

Fixes: #198 

This PR modifies the CLI to prevent overwriting i18n.json with a default template when an unsupported locale is provided. Instead of allowing the file to be overwritten, the CLI now checks for unsupported locales and throws a clear error message if one is detected.

2024-10-17 05:14 UTC, maxprilutskiy commented
Hi @Nithishvb – good attempt!

However, `resave` must remain `true` here: we have a mechanism, that automatically migrates config file to the next version when there's such, whenever `i18n` command is being run.

Here's more info: https://github.com/replexica/replexica/blob/main/packages/spec/src/config.ts

I think the issue might be somewhere in `extendConfigDefinition` function, but that's just a guess.

Also, would be awesome to have a super tiny vitest test, to make sure the fix actually works!

2024-10-17 06:17 UTC, Nithishvb commented
Hi @maxprilutskiy , 

Thanks for the feedback! I'll look into the `extendConfigDefinition` function and ensure resave remains true. I'll also add a vitest test to verify the fix. Let me give it another go!

2024-10-17 18:55 UTC, Nithishvb commented
Hi @maxprilutskiy 

I’ve made the requested changes!

1. Resave remains true as per the migration mechanism, which automatically updates the config file to the next version whenever the i18n command runs. 
2. Also, I’ve added a tiny vitest test to ensure the fix works correctly, covering the unsupported locale scenario.

2024-10-20 18:58 UTC, maxprilutskiy commented on packages/spec/src/config.spec.ts
> +
nice, thanks for adding the test!

2024-10-20 19:10 UTC, maxprilutskiy requested changes
Looks good!

Now, to make the CI/CD checks pass, please:

1. Go to the root of the repo
2. Run `pnpm new`. Select `replexica` AND `replexica/cli`. Then, make sure you trigger the patch version release. (`x.y.Z` <-).
3. Choose a message for your changelog entry.
4. Commit the file that got created, and push it to github.

Looking forward to merging your PR soon!

2024-10-20 19:10 UTC, maxprilutskiy commented on packages/spec/src/config.ts
> +
👏

2024-10-20 19:37 UTC, Nithishvb commented
hey @maxprilutskiy 

I've completed the requested changes and pushed them to GitHub. Looking forward to your review and merging the PR soon!

2024-10-20 23:28 UTC, maxprilutskiy approved these changes
LGTM!

2024-10-20 23:28 UTC, merged