chore: enhance error handling in GitHub Actions workflows
replexica/replexica pull request #282
Opened 2024-11-03 06:37 UTC by partik03

may close #191 

- feat: Added custom error messages for permission and dependency issues.
- feat: Improved guidance for semantic PR title validation in Lint PR.
- feat: Enhanced error handling for build, test, and release steps with actionable feedback.
- chore: Included instructions on resolving common failure scenarios.

2024-11-03 06:38 UTC, partik03 commented
@maxprilutskiy kindly review this PR

2024-11-03 17:01 UTC, maxprilutskiy requested changes
#191 was actually addressed by https://github.com/replexica/replexica/pull/274, for the most part, so allthese changes are not needed anymore

good job updating `exit 1` -> `exit 0`, but the rest is not needed, as essentially it just more code that wouldn't change developer experience much

1. leave exit 1 -> exit 0 changes
2. leave the rest as it was
3. let's merge it

2024-11-03 17:01 UTC, maxprilutskiy commented on .github/workflows/pr-check.yml
> -            exit 1
damn, this is a good catch, well done!

2024-11-03 17:01 UTC, maxprilutskiy commented on .github/workflows/pr-check.yml
> +          fi
additional check is not needed here

2024-11-03 17:01 UTC, maxprilutskiy commented on .github/workflows/pr-check.yml
> +          fi
additional checks is not needed here

2024-11-03 17:01 UTC, maxprilutskiy commented on .github/workflows/pr-lint.yml
> +          exit 1
additional check is not needed here

2024-11-03 17:01 UTC, maxprilutskiy commented on .github/workflows/release.yml
> +            exit 0
that's a good one

2024-11-04 05:38 UTC, partik03 commented on .github/workflows/pr-check.yml
> +          fi
removed

2024-11-04 05:38 UTC, partik03 commented on .github/workflows/pr-lint.yml
> +          exit 1
okay

2024-11-04 05:38 UTC, partik03 commented on .github/workflows/pr-check.yml
> +          fi
okay

2024-11-04 05:38 UTC, partik03 commented
@maxprilutskiy kindly check again

2024-11-04 17:25 UTC, merged

2024-11-04 17:25 UTC, maxprilutskiy commented
@partik03 merged!