feat(cli): implemented the vtt loader
replexica/replexica pull request #328
Opened 2024-11-24 08:06 UTC by partik03

**Summary:**
Should close #294 

- Added VTT loader to handle translations.
- Used require for unsupported TypeScript modules to avoid missing declaration errors.

- Included tests for complex XLIFF structures.

Notes:

added custom type definition file inside types folder

2024-11-24 15:48 UTC, partik03 commented
@maxprilutskiy kindly review this one

2024-12-13 22:55 UTC, maxprilutskiy requested changes

2024-12-13 22:55 UTC, maxprilutskiy commented on .changeset/little-lizards-brake.md
> +"@replexica/cli": minor
I know this isn't ideal, but when the plan is to bump the cli, please bump both `replexica` and `@replexica/cli` packages, and make sure the versions are in sync

2024-12-13 22:55 UTC, maxprilutskiy commented on packages/cli/src/loaders/index.spec.ts
> +        "1#30-31##align:start line:0%": "This is a subtitle",
let's not make `align:start line ` part of the key, feels like it's irrelevant as it's just metadata

2024-12-13 22:55 UTC, maxprilutskiy commented on packages/cli/types/vtt.d.ts
> +}
nice!

2025-01-06 18:10 UTC, maxprilutskiy commented
closing b/c of inactivity, feel free to reopen!

2025-01-06 18:10 UTC, closed without merging