feat(cli): implemented the tmx loader and format changes
replexica/replexica pull request #335
Opened 2024-11-30 11:13 UTC by partik03

Should close #289 

- feat: Implement a new createTmxLoader() function in packages/cli/src/loaders/tmx.ts to handle loading and saving TMX subtitle files
- test: Add two unit tests in packages/cli/src/loaders/index.spec.ts to validate parsing of simple SRT files
- docs: Update @replexica/spec to include the SRT file format specification
- chore: Generate changelogs for both 'replexica' and '@replexica/cli' packages using pnpm new

2024-11-30 20:00 UTC, partik03 commented
@maxprilutskiy please review this one

2024-12-13 22:52 UTC, maxprilutskiy requested changes

2024-12-13 22:52 UTC, maxprilutskiy commented on .changeset/quiet-pets-end.md
> +"@replexica/cli": major
1. please use either patch or minor
2. please bump both `@replexica/cli` and `replexica` whenever you're planning to bump the CLI (we should make this less confusing)

2024-12-13 22:52 UTC, maxprilutskiy commented on packages/cli/src/loaders/tmx.ts
> +}
I'm not sure this is needed / this is the best approach here...

maybe some helper functions from @replexica/spec could help?

2024-12-13 22:52 UTC, maxprilutskiy commented on packages/cli/src/loaders/index.spec.ts
> +  describe('tmx bucket loader', () => {
this looks great! 🔥

2025-01-15 10:35 UTC, closed without merging

2025-01-15 10:36 UTC, maxprilutskiy commented
closing b/c of inactivity